import { PhoneMask } from 'components/common/PhoneInput';

export const MASKS: PhoneMask[] = [
  {
    key: 'ru',
    name: 'Россия',
    prefix: '+7',
    mask: '(***) ***-**-**',
  },
  {
    key: 'kz',
    name: 'Казахстан',
    prefix: '+7',
    mask: '(***) ***-**-**',
  },
  {
    key: 'us',
    name: 'США',
    prefix: '+1',
    mask: '(***) ***-****',
  },
  {
    key: 'ca',
    name: 'Канада',
    prefix: '+1',
    mask: '(***) ***-****',
  },
  {
    key: 'gb',
    name: 'Великобритания',
    prefix: '+44',
    mask: '**** ******',
  },
  {
    key: 'de',
    name: 'Германия',
    prefix: '+49',
    mask: '*** *******',
  },
  {
    key: 'fr',
    name: 'Франция',
    prefix: '+33',
    mask: '* ** ** ** **',
  },
  {
    key: 'it',
    name: 'Италия',
    prefix: '+39',
    mask: '*** *** ****',
  },
  {
    key: 'es',
    name: 'Испания',
    prefix: '+34',
    mask: '*** ** ** **',
  },
  {
    key: 'ua',
    name: 'Украина',
    prefix: '+380',
    mask: '** *** ** **',
  },
  {
    key: 'by',
    name: 'Беларусь',
    prefix: '+375',
    mask: '** ***-**-**',
  },
  {
    key: 'pl',
    name: 'Польша',
    prefix: '+48',
    mask: '*** *** ***',
  },
  {
    key: 'cz',
    name: 'Чехия',
    prefix: '+420',
    mask: '*** *** ***',
  },
  {
    key: 'sk',
    name: 'Словакия',
    prefix: '+421',
    mask: '*** *** ***',
  },
  {
    key: 'at',
    name: 'Австрия',
    prefix: '+43',
    mask: '*** *******',
  },
  {
    key: 'ch',
    name: 'Швейцария',
    prefix: '+41',
    mask: '** *** ** **',
  },
  {
    key: 'nl',
    name: 'Нидерланды',
    prefix: '+31',
    mask: '* ********',
  },
  {
    key: 'be',
    name: 'Бельгия',
    prefix: '+32',
    mask: '*** ** ** **',
  },
  {
    key: 'se',
    name: 'Швеция',
    prefix: '+46',
    mask: '**-*** ** **',
  },
  {
    key: 'no',
    name: 'Норвегия',
    prefix: '+47',
    mask: '*** ** ***',
  },
  {
    key: 'fi',
    name: 'Финляндия',
    prefix: '+358',
    mask: '** *** ** **',
  },
  {
    key: 'dk',
    name: 'Дания',
    prefix: '+45',
    mask: '** ** ** **',
  },
  {
    key: 'pt',
    name: 'Португалия',
    prefix: '+351',
    mask: '*** *** ***',
  },
  {
    key: 'gr',
    name: 'Греция',
    prefix: '+30',
    mask: '*** *** ****',
  },
  {
    key: 'ie',
    name: 'Ирландия',
    prefix: '+353',
    mask: '** *** ****',
  },
  {
    key: 'hu',
    name: 'Венгрия',
    prefix: '+36',
    mask: '** *** ****',
  },
  {
    key: 'ro',
    name: 'Румыния',
    prefix: '+40',
    mask: '*** *** ***',
  },
  {
    key: 'bg',
    name: 'Болгария',
    prefix: '+359',
    mask: '*** *** ***',
  },
  {
    key: 'hr',
    name: 'Хорватия',
    prefix: '+385',
    mask: '** *** ****',
  },
  {
    key: 'rs',
    name: 'Сербия',
    prefix: '+381',
    mask: '** *** ****',
  },
  {
    key: 'tr',
    name: 'Турция',
    prefix: '+90',
    mask: '*** *** ** **',
  },
  {
    key: 'il',
    name: 'Израиль',
    prefix: '+972',
    mask: '**-***-****',
  },
  {
    key: 'ae',
    name: 'ОАЭ',
    prefix: '+971',
    mask: '** *** ****',
  },
  {
    key: 'sa',
    name: 'Саудовская Аравия',
    prefix: '+966',
    mask: '** *** ****',
  },
  {
    key: 'eg',
    name: 'Египет',
    prefix: '+20',
    mask: '*** *** ****',
  },
  {
    key: 'za',
    name: 'ЮАР',
    prefix: '+27',
    mask: '** *** ****',
  },
  {
    key: 'ng',
    name: 'Нигерия',
    prefix: '+234',
    mask: '*** *** ****',
  },
  {
    key: 'cn',
    name: 'Китай',
    prefix: '+86',
    mask: '*** **** ****',
  },
  {
    key: 'jp',
    name: 'Япония',
    prefix: '+81',
    mask: '**-****-****',
  },
  {
    key: 'kr',
    name: 'Южная Корея',
    prefix: '+82',
    mask: '**-****-****',
  },
  {
    key: 'in',
    name: 'Индия',
    prefix: '+91',
    mask: '***** *****',
  },
  {
    key: 'id',
    name: 'Индонезия',
    prefix: '+62',
    mask: '***-****-****',
  },
  {
    key: 'th',
    name: 'Таиланд',
    prefix: '+66',
    mask: '**-***-****',
  },
  {
    key: 'vn',
    name: 'Вьетнам',
    prefix: '+84',
    mask: '*** *** ****',
  },
  {
    key: 'ph',
    name: 'Филиппины',
    prefix: '+63',
    mask: '*** *** ****',
  },
  {
    key: 'sg',
    name: 'Сингапур',
    prefix: '+65',
    mask: '**** ****',
  },
  {
    key: 'my',
    name: 'Малайзия',
    prefix: '+60',
    mask: '**-*** ****',
  },
  {
    key: 'au',
    name: 'Австралия',
    prefix: '+61',
    mask: '*** *** ***',
  },
  {
    key: 'nz',
    name: 'Новая Зеландия',
    prefix: '+64',
    mask: '** *** ****',
  },
  {
    key: 'br',
    name: 'Бразилия',
    prefix: '+55',
    mask: '** *****-****',
  },
  {
    key: 'mx',
    name: 'Мексика',
    prefix: '+52',
    mask: '** **** ****',
  },
  {
    key: 'ar',
    name: 'Аргентина',
    prefix: '+54',
    mask: '** ****-****',
  },
  {
    key: 'cl',
    name: 'Чили',
    prefix: '+56',
    mask: '* **** ****',
  },
  {
    key: 'co',
    name: 'Колумбия',
    prefix: '+57',
    mask: '*** *** ****',
  },
  {
    key: 'pe',
    name: 'Перу',
    prefix: '+51',
    mask: '*** *** ***',
  },
  {
    key: 'uz',
    name: 'Узбекистан',
    prefix: '+998',
    mask: '** ***-**-**',
  },
  {
    key: 'ge',
    name: 'Грузия',
    prefix: '+995',
    mask: '*** ** ** **',
  },
  {
    key: 'am',
    name: 'Армения',
    prefix: '+374',
    mask: '** ******',
  },
  {
    key: 'az',
    name: 'Азербайджан',
    prefix: '+994',
    mask: '** *** ** **',
  },
  {
    key: 'lt',
    name: 'Литва',
    prefix: '+370',
    mask: '*** *****',
  },
  {
    key: 'lv',
    name: 'Латвия',
    prefix: '+371',
    mask: '** *** ***',
  },
  {
    key: 'ee',
    name: 'Эстония',
    prefix: '+372',
    mask: '**** ****',
  },
  {
    key: 'md',
    name: 'Молдова',
    prefix: '+373',
    mask: '**** ****',
  },
  {
    key: 'cy',
    name: 'Кипр',
    prefix: '+357',
    mask: '** ******',
  },
  {
    key: 'is',
    name: 'Исландия',
    prefix: '+354',
    mask: '*** ****',
  },
  {
    key: 'lu',
    name: 'Люксембург',
    prefix: '+352',
    mask: '*** *** ***',
  },
  {
    key: 'si',
    name: 'Словения',
    prefix: '+386',
    mask: '** *** ***',
  },
];
